# Builds Windows x64 and ARM variants

name: Visual Studio

on: [push]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        configurations: [Debug, Release]
        platforms: [x64, ARM64]

    env:
      SOLUTION_FILE_PATH: HelloWebGPU.sln
      BUILD_CONFIGURATION: ${{matrix.configurations}}
      BUILD_PLATFORM: ${{matrix.platforms}}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:Platform=${{env.BUILD_PLATFORM}} ${{env.SOLUTION_FILE_PATH}}
