# Builds Mac x64 and ARM variants

name: Xcode (macOS)

on: [push]

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        destination: ["platform=macOS,arch=x86_64", "platform=macOS,arch=arm64"]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: xcodebuild clean build -destination '${{matrix.destination}}'
